CountDownPreLobby: 60  
Mob-Spawn-Range: 10
Item-Spawn-Range: 10
Remove-Armor-Stands: 30
Chest-Particle-Range: 10
Join-Reward: false
Time-Reward: 30
Anti-Void: true
Plus-Or-Remove: "+"
Local-Time-Day: 1
Local-Time-Hour: 1
Dispenser-Range: 30
Loot-Table-Limit: 10
Maintenance: false
Data-Base:
    Enabled: false     
    Host: "sql9.freesqldatabase.com"
    Puerto: 3306
    BaseDeDatos: "sql9581887"  
    Usuario: "sql9581887"
    Clave: "6QGbkafXab"       
Maps-Created:
    List:
    - example
Maps-Locked:
    List:    
    - example
HeadShoot-World:
    List:
    - example
Regen-Explosion:
    List:
    - example    
Maps-Points:
    List:
    - example  
Random-Reward:
    List:
    - example1
    - example2    
Max-Animation: 1    
Min-Animation: 2    
Worlds-Animation:
    List:
    - example1
    - example2        
FallingBlock-Remove-If-Touch-Ground:
    List:
    - example1
    - example2 
 