version: 2.13.4
name: MineGame
main: me.nao.main.mg.Minegame
api-version: 1.16
author: NAO2706
description: SubGames into Minecraft
softdepend: [NBTAPI]


commands: 
     minegame:
        description: Comando de op
        aliases:
        - minigame
        - nao-game
        - mg
 