version: 1.71.2
name: MineGame
main: me.nao.main.game.Minegame
api-version: 1.19
author: NAO2706
description: SubGames into Minecraft
softdepend: [NBTAPI]


commands: 
     minegame:
        description: Comando de op
        aliases:
        - minigame
        - nao-game
        - mg
 